image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules

stages:
  - test
  - lint
  - deploy

jest-tests:
  before_script:
    - yarn install --frozen-lockfile
  stage: test
  script:
    - yarn jest --ci

eslint:
  stage: lint
  script:
    - yarn lint

expo-deploy:
  before_script:
    - sysctl -w fs.inotify.max_user_watches=524288
  stage: deploy
  only:
    refs:
      - master
  script:
    - apk add --no-cache bash
    - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - yarn expo publish --non-interactive