/* Login Actions */
const LOGIN_PENDING = "LOGIN_PENDING";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";

/* Register Navigation action */
const GO_TO_REGISTER = "GO_TO_REGISTER";

/* Register Actions */
const REGISTER_PENDING = "REGISTER_PENDING";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_ERROR";

/* Navigation Action */
const NAVIGATE_BACK = "NAVIGATE_BACK";

export {
  LOGIN_PENDING,
  LOGIN_ERROR,
  LOGIN_SUCCESS,
  GO_TO_REGISTER,
  REGISTER_ERROR,
  REGISTER_PENDING,
  REGISTER_SUCCESS,
  NAVIGATE_BACK
};
