/* Login Actions */
const LOGIN_PENDING = "LOGIN_PENDING";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";

const LOGOUT = "LOGOUT";
/* Register Navigation action */
const GO_TO_REGISTER = "GO_TO_REGISTER";

/* Register Actions */
const REGISTER_PENDING = "REGISTER_PENDING";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_ERROR";

/* Navigation Actions */
const NAVIGATE_BACK = "NAVIGATE_BACK";
const GO_TO_PAY = "GO_TO_PAY";
const GO_TO_COLLECT = "GO_TO_COLLECT";

/* Payments Actions */
const PAYMENT_PENDING = "PAYMENT_PENDING";
const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
const PAYMENT_ERROR = "PAYMENT_ERROR";

/* Collect Actions */
const SET_WALLET_AMOUNT = "SET_WALLET_AMOUNT";

export {
  LOGIN_PENDING,
  LOGIN_ERROR,
  LOGIN_SUCCESS,
  LOGOUT,
  GO_TO_REGISTER,
  REGISTER_ERROR,
  REGISTER_PENDING,
  REGISTER_SUCCESS,
  NAVIGATE_BACK,
  GO_TO_COLLECT,
  GO_TO_PAY,
  PAYMENT_PENDING,
  PAYMENT_SUCCESS,
  PAYMENT_ERROR,
  SET_WALLET_AMOUNT
};
