const REGISTER = "REGISTER";
const LOGIN = "LOGIN";
const HISTORY = "HISTORY";
const PAYMENT = "PAYMENT";
const PROFILE = "PROFILE";
const HOME = "HOME";

const PAY = "PAY";
const COLLECT = "COLLECT";

/* Containers */
const MAINSTACK = "MAIN_STACK";
const AUTHSTACK = "AUTH_STACK";
const WALLETSTACK = "WALLET";

export {
  REGISTER,
  LOGIN,
  HISTORY,
  PAYMENT,
  PROFILE,
  PAY,
  COLLECT,
  MAINSTACK,
  AUTHSTACK,
  WALLETSTACK
};
